enum class TokenType{
    WHILE, IDENTIFIER, NUMBER, LESS, LESS_EQUAL, EQUAL, SEMICOLON, RIGHT_PAREN, LEFT_PAREN,
    EOF, LEFT_BRACE, RIGHT_BRACE, PLUS, MINUS, STAR, SLASH, EQUAL_EQUAL, BANG, BANG_EQUAL,
    STRING, VAR, PRINT, IF, ELSE, TRUE, FALSE, NIL
}
